### ISSUE TITLE
MeshColliders

### ISSUE THREAD

**Issue by htxqteam1** [strangeways-dev/sw_CSG#1]

**Comment by strangeways-dev** [comment]
> _No description provided._

Hi, you deleted your comment so not sure if you still need help.
Think of the BoxCollider as just the bounding box for the Mesh so even thought the Effector/Effectee may use BoxColliders the boolean operations still actually use the meshes. The generated mesh that is generated will have a mesh collider and use the newly generated mesh for its collisions so if you punch a hole in a wall for example the collider will also have a hole.

Hope this helps, please let me know if I you need anything else.

**Comment by strangeways-dev** [comment]
Actually I may have found a way to change the collider, I will update in the next hour.

**Comment by strangeways-dev** [comment]
> _Hi, thank you for the amazing work. I am curious to know if this will work with mesh colliders? The idea I have is a plane that cuts a terrain, if they interesect, the plane will cut a hole at the intersection of the terrain, do you think it will work? I have tried the repo using mesh collider but it seems to not be working as smoothly vs primitives shapes. Not sure if I did anything wrong. Would like to have you input on this, thank you very much once again!_

Thank you and thanks for joining me! I have just implemented MeshColliders now. I will update the repo shortly and leave another message here when I have done so.

For the plane quiestion, plane subtractions are currently not possible, my solution would be to use a very thin cube for the time being.

**Comment by strangeways-dev** [comment]
All Collider types now work including MeshColliders.
The latest release is now available here:
https://github.com/strangeways-dev/sw_CSG/releases/tag/v2.1.1-alpha

Let me know if you need anything else, cheers!
